# Generated by Django 3.1 on 2020-09-06 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=255)),
                ('recipients_name', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('recipients_phone', models.CharField(max_length=11)),
                ('recipients_id', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('i', 'Initiated'), ('a', 'Assigned'), ('d', 'Delivered'), ('c', 'Cancelled')], default='i', max_length=10)),
                ('initialization_date', models.DateTimeField(auto_now_add=True)),
                ('assignment_date', models.DateTimeField(blank=True, default=None)),
                ('delivery_date', models.DateTimeField(blank=True, default=None)),
                ('distributor', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
