# Generated by Django 3.1 on 2020-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200907_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'supervisor'), (3, 'distributor')], default='3'),
        ),
    ]
